### ISSUE TITLE
你好，方便告诉下训练时间嘛？

### ISSUE THREAD

**Issue by zqlsnr** [Le-Xiaohuai-speech/DPCRN_DNS3#1]
你好，祝贺你取得了这么好的成绩！
试了预训练模型，感觉效果很nice，想问下训练时间

**Comment by Le-Xiaohuai-speech** [comment]
你好，


实验是单卡1080Ti，batch size 8 ，一段音频5s，25epoch左右吧，1-2天训练完。
多卡的并行训练有一点问题，由于没啥时间debug就用单卡训练了。
datagenerator那边，也没有用多进程读数据，就直接上固态硬盘。当然机械盘训练时长应该也差不多的。
此外，LSTM也应该用CUDNNLSTM，应该会更快一点吧，但当时训练时候并没有考虑到。


乐笑怀

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月14日(周二) 晚上6:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Le-Xiaohuai-speech/DPCRN_DNS3] 你好，方便告诉下训练时间嘛？ (#1)




 
你好，祝贺你取得了这么好的成绩！
 试了预训练模型，感觉效果很nice，想问下训练时间
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqlsnr** [comment]
你好，
谢谢您的回复！
data_loader.py的# 170 和 #171 行，如果是训练音频是5s，会出现clean_s 和 noise_s为空的情况，本地的tensorflow版本是1.15.0
![image](https://user-images.githubusercontent.com/83391979/133378190-8a3cfe33-45f3-4e0a-921f-baef21a3b94a.png)

**Comment by Le-Xiaohuai-speech** [comment]
你好,
请问这个情况是偶然出现还是一开始就错了。如果是数据长短不一是一种可能原因。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月15日(周三) 中午1:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Le-Xiaohuai-speech/DPCRN_DNS3] 你好，方便告诉下训练时间嘛？ (#1)




 
你好，
 谢谢您的回复！
 data_loader.py的# 170 和 #171 行，如果是训练音频是5s，会出现clean_s 和 noise_s为空的情况，本地的tensorflow版本是1.15.0
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqlsnr** [comment]
你好，
这个情况是一开始就有的。
我用的clean和nosie的数据都是用DNS-Challenge的noisyspeech_synthesizer_multiprocessing.py生成的5秒音频数据，应该是Begin_S和Begin_N的值导致 #170 clean_s 和 #171 nosie_s 为空。
        Begin_S = int(np.random.uniform(0,30 - self.length_per_sample)) * self.fs
        Begin_N = int(np.random.uniform(0,30 - self.length_per_sample)) * self.fs
当用每段30s的clean和nosie音频时，args.second 还为5的时候，就没有这个情况！
还有为什么要用30 - self.length_per_sample呢？

**Comment by Le-Xiaohuai-speech** [comment]
你好，
数据生成的代码过于久远了。当时有很多额外的条件分支处理脏数据，删减的时候没考虑这些。
30-self.length_per_sample，应该是以DNS数据为基础，从30s里面随机截取5s，音频开始的地方应该是在0-25s随机的。这个30可能需要根据你使用的数据更改。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月15日(周三) 晚上8:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Le-Xiaohuai-speech/DPCRN_DNS3] 你好，方便告诉下训练时间嘛？ (#1)




 
你好，
 这个情况是一开始就有的。
 我用的clean和nosie的数据都是用DNS-Challenge的noisyspeech_synthesizer_multiprocessing.py生成的5秒音频数据，应该是Begin_S和Begin_N的值导致 #170 clean_s 和 #171 nosie_s 为空。
 Begin_S = int(np.random.uniform(0,30 - self.length_per_sample)) * self.fs
 Begin_N = int(np.random.uniform(0,30 - self.length_per_sample)) * self.fs
 当用每段30s的clean和nosie音频时，args.second 还为5的时候，就没有这个情况！
 还有为什么要用30 - self.length_per_sample呢？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqlsnr** [comment]
好的，谢谢你~
