### ISSUE TITLE
in data_loader.py ，the clean speech which  to be saved   is right？

### ISSUE THREAD

**Issue by l2009312042** [Le-Xiaohuai-speech/DPCRN_DNS3#5]
the clean speech is saved after rir process， i  think it should save the origin clean speech before rir process ，is that right？

**Comment by Le-Xiaohuai-speech** [comment]
yes, the clean speech is convolved with RIRs at training stage. I used the clean speech without&nbsp;reverberation generated from DNS script.

---Original---
From: ***@***.***&gt;
Date: Fri, Nov 19, 2021 13:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Le-Xiaohuai-speech/DPCRN_DNS3] in data_loader.py ，the clean speech which  to be saved   is right？ (Issue #5)




 
the clean speech is saved after rir process， i  think it should save the origin clean speech before rir process ，is that right？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by l2009312042** [comment]
thanks for the reply. so you don't use the data_loader.py  to create the training data ?
 i encounter another question,  for same denoisenet ,  
1 when i use the data  created from data_loade.py，the net don't convergence, i don't use the rir step to process clean speech.
the si-snr  <  -40,it's so bad 
2 but  change  the traing data to dns script created, the net convergence ?  the si-snr  >  20
i have no idea about the difference ?  can you give me some advice about this?

**Comment by Le-Xiaohuai-speech** [comment]
the data-loader cut the 30s audio from DNS data into shorter clips (about 8s for a 11G 1080ti). Maybe your audio is shorter than 30s and there are too much silent frames in the speech clips.



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 19, 2021 16:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Le-Xiaohuai-speech/DPCRN_DNS3] in data_loader.py ，the clean speech which  to be saved   is right？ (Issue #5)




 
thanks for the reply. so you don't use the data_loader.py  to create the training data ?
 i encounter another question,  for same denoisenet ,
 1 when i use the data  created from data_loade.py，the net don't convergence, i don't use the rir step to process clean speech.
 the si-snr  <  -40,it's so bad
 2 but  change  the traing data to dns script created, the net convergence ?  the si-snr  &gt;  20
 i have no idea about the difference ?  can you give me some advice about this?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by l2009312042** [comment]
thanks,
